coverage:
  status:
    project:
      default:
        target: auto
        threshold: 5%
    patch:
      default:
        target: auto
        threshold: 100%

ignore:
  - "**/*.md"
  - "docs/**/*"
  - "*.yml"
  - "*.toml"
  - "Makefile"
